name: Deploy NestJS API
on:
    push:
        branches: [stg_main]
jobs:
    e2e_test:
        runs-on: [ubuntu-latest]

        if: (github.ref == 'refs/heads/stg_main')
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            # - name: Install dependencies
            #   run: npm install
            # - name: Run end-to-end tests
            #   run: |
            #       npm run test:e2e
            #       if [ $? -ne 0 ]; then
            #         echo "End-to-end tests failed. Exiting."
            #         exit 1
            #       fi

    deploy:
        needs: e2e_test
        runs-on: [ubuntu-latest]
        if: (github.ref == 'refs/heads/stg_main')
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: SSH into server and run sync.sh
              run: |
                  sshpass -p ${{ secrets.TEST_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ubuntu@59.12.54.63 << EOF
                    cd /home/backendtestuser/Repositories/CNDP-SKIN-v2/
                    git pull origin stg_main
                    sudo node run-migration.cjs
                    sudo npm install
                    echo "Building application"
                    sudo npm run build
                    echo "Restarting the application using PM2"
                    pm2 restart ecosystem.config.js
                    echo "Deployment process completed"
                  EOF
        # Removing Old action
    cleanup-action:
        runs-on: [ubuntu-latest]
        needs: deploy
        continue-on-error: true
        steps:
            - name: Cleaning existing Actions
              run: |
                  echo "Removing old workflow runs..."
                  RUNS=$(curl -s -X GET -G "https://api.github.com/repos/${{ github.repository }}/actions/runs" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          | jq -r '.workflow_runs[] | select(.id != ${{ github.run_id }}) | .id')

                  for run in $RUNS; do
                    echo "Deleting workflow run $run"
                    curl -X DELETE -G "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run" \
                      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json"
                  done

            # sudo docker run -d -p 2024:2024 --name test-container-container chowisbackend/test-container:latest
            # sudo docker pull chowisbackend/test-container:latest
            # certbot certonly --dns-google --agree-tos \ -d "*.example.com"git
